# Generated by Django 4.2.7 on 2023-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
